### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by latessa** [GOMC-WSU/gomc-wsu.github.io#1]
I noticed these broken  links as I was moving website content to the new repository:

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/publications.html#L108

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/publications.html#L480

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/publications.html#L496

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/publications.html#L510

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/publications.html#L526

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/about.html#L182

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/about.html#L223

https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/c7dbe2b1d80c58326e671dcb28c05769f257fc09/features.html#L57

**Comment by LSchwiebert** [comment]
A number of the broken links on the publications page are pointing to the poster pdfs. Probably just need to update their location, assuming you've already uploaded the images.

For the Silicon Mechanics link on the About tab, let's use their homepage: https://www.siliconmechanics.com/

**Comment by LSchwiebert** [comment]
The FOMMS link on the publications page can be updated to the following:

https://axial.acs.org/chemical-engineering-and-industrial-chemistry/journal-of-chemical-engineering-data-fomms-special-issue

**Comment by latessa** [comment]
After having updated the poster links, the only broken links remaining now are these two:

<a href="https://gitter.im/GOMC_WSU">GOMC Gitter</a> 
<a href="http://gregchung.github.io/CoRE-MOFs/">CoRE database</a>

**Comment by LSchwiebert** [comment]
I think the GOMC Gitter link has changed to: https://app.gitter.im/#/room/#GOMC_WSU_Lobby:gitter.im

At least, that is working for me. @jpotoff will have to figure out what they want for the CORE database link. We probably need to update to MoSDeF, but not sure how to reword and relink.

**Comment by latessa** [comment]
Thanks.  I've updated the GOMC Gitter link.

**Comment by latessa** [comment]
The updated CORE database link is now fixed.  That was the last broken link, so I'm marking this issue as complete.
