### ISSUE TITLE
Link Checker Tools Reports A Link Having Recently Become Broken

### ISSUE THREAD

**Issue by latessa** [GOMC-WSU/gomc-wsu.github.io#5]
On its most recent run, the [link checker](https://github.com/GOMC-WSU/gomc-wsu.github.io/actions/runs/6287042503), which runs on a weekly schedule, reports that the [GPU Research](https://github.com/GOMC-WSU/gomc-wsu.github.io/blob/02b814e69b5fa32ec523fdf8edc5adc70bb388b4/about.html#L211C16-L211C16) link in the Grants section of the [About ](https://gomc-wsu.org/about.html)page has stopped working.

**Comment by GOMC-WSU** [comment]
I tried to edit the about.html file directly but it was not verified. Can you take a look? I removed the link as it's obsolete and I can't find an alternative.

**Comment by GOMC-WSU** [comment]
You can find the test build here: https://github.com/GOMC-WSU/gomc-wsu.github.io/actions/runs/6329415483/job/17189645809

It is also giving a warning about the node it is running on. Can we fix this?

**Comment by GOMC-WSU** [comment]
Closing this issue as the about page has been patched to remove the broken link.

**Comment by GOMC-WSU** [comment]
Closing this issue as the about page has been patched to remove the broken link.
